openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /cocktails/:
    get:
      operationId: cocktails_list
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - cocktails
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCocktailsList'
          description: ''
    post:
      operationId: cocktails_create
      tags:
      - cocktails
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cocktails'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Cocktails'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Cocktails'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cocktails'
          description: ''
  /cocktails/{id}/:
    get:
      operationId: cocktails_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this cocktails.
        required: true
      tags:
      - cocktails
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cocktails'
          description: ''
    put:
      operationId: cocktails_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this cocktails.
        required: true
      tags:
      - cocktails
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cocktails'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Cocktails'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Cocktails'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cocktails'
          description: ''
    patch:
      operationId: cocktails_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this cocktails.
        required: true
      tags:
      - cocktails
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCocktails'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCocktails'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCocktails'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cocktails'
          description: ''
    delete:
      operationId: cocktails_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this cocktails.
        required: true
      tags:
      - cocktails
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /drunk:
    post:
      operationId: drunk_create
      tags:
      - drunk
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    Cocktails:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        image_url:
          type: string
          format: uri
          writeOnly: true
        image:
          type: string
          format: uri
          nullable: true
        name:
          type: string
          nullable: true
          maxLength: 255
        instruction:
          type: string
          nullable: true
        alcoholic:
          type: boolean
        ingredients:
          type: string
          nullable: true
      required:
      - id
    PaginatedCocktailsList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Cocktails'
    PatchedCocktails:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        image_url:
          type: string
          format: uri
          writeOnly: true
        image:
          type: string
          format: uri
          nullable: true
        name:
          type: string
          nullable: true
          maxLength: 255
        instruction:
          type: string
          nullable: true
        alcoholic:
          type: boolean
        ingredients:
          type: string
          nullable: true
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
