# Generated by Django 5.1.5 on 2025-01-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cocktails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("instruction", models.TextField(blank=True, null=True)),
                ("alcoholic", models.BooleanField(default=False)),
                ("ingredients", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
